# Generated by Django 5.1.4 on 2024-12-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
