# Generated by Django 5.1.4 on 2024-12-15 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loja.product')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loja.shoppinglist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shopping_list', 'product'), name='unique_shopping_list_product')],
            },
        ),
    ]
