# Generated by Django 5.1.4 on 2024-12-16 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0004_shoppinglistproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistproduct',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shoppinglistproduct',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Loja.shoppinglist'),
        ),
    ]
