# Generated by Django 5.1.4 on 2024-12-16 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loja', '0006_recipe_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Loja.product'),
            preserve_default=False,
        ),
    ]
